# Generated by Django 5.1.6 on 2025-03-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='is_active',
            field=models.BooleanField(choices=[(0, 'Не опубликовано'), (1, 'Опубликовано')], default=1),
        ),
    ]
