# Generated by Django 5.1.6 on 2025-04-28 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_comment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, height_field=300, null=True, upload_to='comments/%Y/%m/%d', verbose_name='Изображение', width_field=300),
        ),
    ]
