# Generated by Django 4.2.7 on 2025-05-27 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0007_alter_comment_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'permissions': [('can_edit_other_comments', 'Может редактировать чужие комментарии')], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комменатрии'},
        ),
    ]
